name: on push to main

on:
  push:


jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - id: docker-publish
        uses: pangzineng/Github-Action-One-Click-Docker@1.1.1
        with:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_REGISTRY_URL: ghcr.io
          DOCKER_NAMESPACE: ${{ github.repository }}

