name: on push to main

on:
  push:


jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: paulhatch/semantic-version@v5.4.0

